### ISSUE TITLE
task: implement storage-backed log writer

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#1148]
Currently we only have the in-memory and no-op implementations:

https://github.com/influxdata/platform/blob/a6c9ecd452c7d4c92dc17477e1f8950fde205b83/task/backend/inmem_logreaderwriter.go#L22-L24

https://github.com/influxdata/platform/blob/a6c9ecd452c7d4c92dc17477e1f8950fde205b83/task/backend/store.go#L242-L244

We need to implement a LogWriter that works with the storage.PointsWriter interface: https://github.com/influxdata/platform/blob/a6c9ecd452c7d4c92dc17477e1f8950fde205b83/storage/points_writer.go#L5-L8

**Comment by lyondhill** [comment]
Movement on making a `platform.PointsWriter` is in progress that unifies the differences between the enterprise points writer and the open source. I think We should wait to build this until that unification work is complete.

**Comment by mark-rushakoff** [comment]
I'm pretty sure that's accurate. @aanthony1243 can you confirm that your change will allow one points writer interface that works for both enterprise and OSS?

**Comment by aanthony1243** [comment]
@mark-rushakoff  I'm not sure if @lyondhill  is referencing the same work.  I was going to solve the issue for `to` by writing a ProxyPointsWriter  that satisfies the platform PointsWriter  but translates the points to `BatchWrite` types and uses the existing `idpe.PointsWriter` on the backend.   Not sure if that solves all problems generally and it's not very performant either.  

However, I believe the difference exists because in `idpe` writes are enqued in Kafka so this may be the only right solution.

**Comment by mark-rushakoff** [comment]
Closed by #1351.
