### ISSUE TITLE
convert /authorization endpoint error to platform error

### ISSUE THREAD

**Issue by kelwang** [influxdata/platform#1290]
sub task https://github.com/influxdata/platform/issues/897

**Comment by bednar** [comment]
Hi @kelwang,

I have a small issue with this fix. When I trying update Authorization status by HTTP endpoint "/api/v2/authorizations/033203647c06a000" the response is:

```json
{"code":"internal error","message":"a panic has occurred","error":"runtime error: invalid memory address or nil pointer dereference"}
```
This is caused by [updateAuthorization() function](https://github.com/influxdata/platform/blob/6eca18fc4e1282f6fd3ca633e5c225bd2a9f5dbe/bolt/authorization.go#L372) that will return **platform.Error**, but [c.db.Update(func(tx *bolt.Tx)](https://github.com/influxdata/platform/blob/6eca18fc4e1282f6fd3ca633e5c225bd2a9f5dbe/bolt/authorization.go#L367) requires "go plain error".

Please, can you look at this problem?

**Comment by kelwang** [comment]
hi @bednar, I created a new issue for this. https://github.com/influxdata/platform/issues/2234
