### ISSUE TITLE
Add support for increase function

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#302]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#217  

https://github.com/influxdata/influxdb/issues/7076

Probably looks something like this:

```
increase = (table=<-) => 
    difference(table, nonNegative:true)
        |> cumulativeSum()
```

See also https://prometheus.io/docs/querying/functions/#increase.

**Comment by adamperlin** [comment]
@aanthony1243 should we leave open?

**Comment by aanthony1243** [comment]
nope, this is done.

**Comment by nathanielc** [comment]
This issue is not quite complete:

1. We need to add the `increase` function as a built in function, not just part of the test cases.
2. We need a specific test case for the behavior described in this comment https://github.com/influxdata/ifql/issues/217#issuecomment-379323490 Related to how increase works when the counter resets.
