### ISSUE TITLE
deleting the org that has buckets 

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#417]
should we ask for confirmation before removing the org that has buckets before deleting them?

**Comment by pauldix** [comment]
The API shouldn't ask for conformation, but the user interface should. If deleting an org, all data underneath it would also get deleted. But this does raise something I was thinking about, which is to mark for deletion rather than actually deleting. Basically, flag any deleted items as deleted so they wouldn't show up in gets of those types of resources. But have another method to show which things are flagged for deletion. Then have some grace period (like 24h or something) to actually run the delete in the background. If we did this we'd probably need to make it an option in the API to do the delete synchronously and right away.

I'd like to hear @timhallinflux, @rbetts, @goller, and @nhaugo sound off on this one too.

**Comment by gshif** [comment]
- Create an org:
> requests.post('http://localhost:9999/v1/orgs', data='{"name": "onetest"}')
   returns : [{u'id': u'027ea23a9df99000', u'name': u'onetest'}]
- Create a bucket:
> requests.post('http://localhost:9999/v1/buckets', data='{"name":"bucket_1","organizationId":"027ea23a9df99000"}')
 - Delete an org:
> requests.delete('http://localhost:9999/v1/orgs/027ea23a9df99000')
- Get bucket:
> requests.get('http://localhost:9999/v1/buckets')
   headers = {'Date': 'Sat, 18 Aug 2018 01:11:18 GMT', 'X-Influx-Error': 'organization not found', 'Content-Length': '0', 'X-Influx-Reference': '1'}

**Comment by gshif** [comment]
With the latest idpe master ("c37f7c3af9de1b624f17b7c7cb67592f138dadf9") I am not seeing the issue, i.e.
- Create an org
- Create bunch of buckets that belong to this org
- Delete org (all of the reference for the org are removed from etcd store: index/org/id, index/org/name, index key (Organizationv1).
- Get all of the buckets using either `influx` or `rest api` command. It won't return an error, but an empty list in this case.

**Comment by gshif** [comment]
There are still some questions that need to get answered:
 - have another method to show which things are flagged for deletion?
 - need to make it an option in the API to do the delete synchronously and right away?
See original Pauls comment

**Comment by goller** [comment]
- [ ] add delete of organization to swagger
- [ ] place a stub where an org's buckets are deleted (hook into storage async work)

**Comment by goller** [comment]
Closed for #1837
