### ISSUE TITLE
Add now function

### ISSUE THREAD

**Issue by pauldix** [influxdata/platform#46]
The language needs a function to get the current time. For example if you want to have a default value in a user defined function:

```
getMeasurement = (db, start, stop=now()) => {
  from(db:db)
     |> range(start:start, stop:stop)
}
```

**Comment by nathanielc** [comment]
Some questions have come up as to what the `now()` function should return: Should it be the current system time? Should it be the relative time of the script execution?

Taking a step back we have two concepts that we make sure play nice:

* options
* the concept that a script executes relative to a specific time.

Having a global  reference time for a script allows duration literals to be coerced to time literals by examining the reference time of the script.

By default the reference time of a script is the current system time when the query is executed. 
It must be possible to execute a script for another time, say I want to run a query as if it were 5m ago.
The plan is to use the `now` option to do so. See #37 

This means we need the ability to access both the reference time of the script and the current system time.

I propose that instead of a `now()` function that we have a function `system.time()` that returns the current time and an option `now` that is the global reference time for the script.

So by default a script execution looks like this.

```
option now = system.time() // this is not required to be present in all scripts

from(db:"mydb")
     |> range(start: -1m, stop:now)
```

To change the `now` time simply assign the option a new value.

```
option now = system.time() - 5m // run the script lagged from the current system time.

from(db:"mydb")
     |> range(start: -1m, stop:now)
```

```
option now = truncate(time:system.time(), duration:1h) // run the script relative to the start of the previous hour.

from(db:"mydb")
     |> range(start: -1m, stop:now)
```

The task system would override any user defined now time to be the scheduled run time. This means that users should not be expected to define the `now` option on their own but rather let the task system manage it for them.

See also #24 for discussion about options and their behavior.
