### ISSUE TITLE
Design how imports/namespaces work in Flux

### ISSUE THREAD

**Issue by nathanielc** [influxdata/platform#510]
The current SPEC does not define how import works.

Things in scope:

* Add syntax for `imports` into Flux
* Import builtin packages
* Using the imported package as a "namespace"
* What does the import path mean?

Things not in scope:

* Given an external import path, how do I get that package?
* Importing external packages
* Defining external packages
* Package versioning

Things to explore:

* Do we need to support major version numbers in the import path?

**Comment by mark-rushakoff** [comment]
Don't we need a way to store packages serverside, and share them with other users or organizations?

Maybe the import style needs to be more hierarchical, like `import "com.example.apps/anomalyDetection"`.

If imports are path-based, am I supposed to know the file layout on the flux server? Or can I only use path-based imports when I'm running a flux server myself, directly connecting to storage nodes?

**Comment by jlapacik** [comment]
@mark-rushakoff you make a good point. This was assuming you submit queries to a local flux interpreter which might not be the case. We could interpret import paths as relative to a specific location like they are in Go. Or come up with a similar way of mapping package name to package location.

**Comment by pauldix** [comment]
I'm strongly in favor of option #2. I think it's simpler and less burdensome for the user. Also, I don't anticipate Flux projects will be massive. They're meant to be lightweight, unlike massive Go projects.

Since it is lighter weight, would it make more sense to just have the keyword be the same as what we're calling the thing? That is, instead of `package` do `namespace foo`. 

I could also see a pattern emerging where people would have a directory of files, but explicitly create a package of them by doing something like this. Assume this file layout:

```
foo/package.flux
foo/sweet_code.flux
foo/more_sweet_functions.flux
```

With the file `foo/package.flux` just being:

```
namespace foo

import (
  // implies that the relative path is relative to where package.flux is
  // not where this is being executed from
  "./sweet_code.flux",
  "./more_sweet_code.flux"
)
```

Then to use the whole package do:

```
import "foo/package.flux"
```

I guess that adds an extra step rather than just assuming that all files in the same dir are in the same package/namespace.

For @mark-rushakoff's question, I think this is more a question of how the runtime handles caching of foreign imports? If you're running the `flux` interpreter on your laptop, I would guess that you could import from builtin namespaces, local directories, or github like:

```
import (
  "math",
  "./foo/package.flux"
  "github.com/pauldix/bar/package.flux"
)
```

In my examples I'm always having the relative path be to relative to where the file is located, rather than the working directory of where the `flux` interpreter was invoked.

For flux scripts that you submit to a server to be run, the implication is that you would always import either builtin scripts or scripts that can be retrieved over the network (like on github). The server could have a configuration to point to a flux home directory and look for packages there.

**Comment by jsternberg** [comment]
I too would like to see some more writing on the server-side mechanics for how packages work as I think it's much more strongly part of the underlying problem than any syntax.

I'm pretty against option 2. There are a lot of edge cases that I think aren't represented there. A few off the top of my head:

1. The actual file defacto becomes part of the public interface and, for compatibility, the location of functions can't be changed.
2. In order to allow for separation of code into different files, there will need to be a way for one file to import another file and export it. This is pretty common in python and ruby where you have one package that implicitly imports the rest of them.
3. Namespaces will conflict with each other between different packages and various combinations of different packages will not compile.
4. It allows pollution of the global namespace.

All of these result in some pretty messy stuff going on. But, while I have a lot of thoughts on the syntax portion of it, I think it's more important to get some of the requirements and mechanics behind how it would work. Nothing too fancy, but just a little forethought to how this change would affect the spec.

For example, where do the resources come from? Will we require the server administrator to include all of the available packages or will we allow remote downloading of resources? Do the various scripts that use the same resource use the same version when we figure out versioning, or are they all independently versioned? Mark already brought up a few of these and I think it might be helpful to define a name for the import mechanism and describe how it might function. If I were to do local development on a query and were to compile it using only local packages, how would I get my work to be pushed to the server so it could access the same files I just used?

And the final question is how is this specified in the spec? I think this has other implication too. Right now when you create a function, it acts as a template that then gets inserted wherever the function is used which basically amounts to inlining everything. Is that how we're going to handle package functions too? If it is, then that means it is going to mostly be the parser's job to deal with imports, inline the results, then strip anything that isn't being used.

I don't think it's a good idea for us to assume that flux projects won't be complex. I think it'll get us into trouble later if we assume that namespaces are less complicated and that flux projects won't need the kind of code management that normal programming languages require.

I do think we should consider using something similar to what vgo has decided. While there might be some controversy over it and SAT solvers, I think we can declare that a SAT solver is too much for something like flux. But the simple version chooser might be perfect for us as all of the information about versioning and dependencies goes into a single file that gets uploaded to the server.

**Comment by pauldix** [comment]
@mark-rushakoff The flux interpreter on your laptop is just like python, ruby, or sh. Flux can work with data from local files (like CSV) or other remote data sources, so running the platform (idp) isn't a requirement at all.

As for the registry, it was already something that was on the roadmap (at least the one in my head). I'd prefer to push that out to Github or something else as much as possible, but we could create a registry in the platform API for convenience at some point. I was thinking the import syntax for non-builtin-packages would require a version. Like:

```
import "github.com/pauldix/foo/package.flux", "1.1"
import "github.com/pauldix/bar/package.flux", ">=1.0"
import "github.com/pauldix/asdf/package.flux", "master"
import "github.com/pauldix/jkl/package.flux", "36936ecd07175cb3698ad340ab9dd2c8f4f353cd"
```

**Comment by nathanielc** [comment]
I'd like to change the direction of the discussion if I can. There are some things we have labels as out of scope for this issue, we can come back to these things later. The only concern is that, what we specify now leaves the door open for the various possibilities we have been discussing.

This issue is primarily focused on the behavior of importing namespaces for use in the current code.

Some questions that we should specify:

* Can assignment be made into an imported namespace?

      import "foo"
      foo.bar = 42


* Do we want to support relative imports? 

      import "./sibling"

    Independent of what that means on the file system, is that a valid concept we want to support?

* What are valid characters in an import path?
   Should we disallow path separators? Is whitespace OK? is it case sensitive?
   
* Can I refer to imported namespaces of namespaces I import?

      // foo.flux
      import "math"
      // Take the sine of _value
      sin = (table=<-) => table |> map(fn:(r) => math.sin(v: r._value))

      // main.flux
      import "foo"
      // Use foo's math namespace?
      s42 = foo.math.sqrt(42)

* Can namespaces modify options?
* Is there a special `main` namespace? If so what can/can't it do? Why is it special?
* Can you import all the identifiers from a namespace into the current namespace? What is the syntax for that? Python uses `from foo import *` Go uses `import . "foo"`
* Can you rename the imported namespace? What is the syntax for that?  Python's `import foo as bar` or Go's `import bar "foo"` something else?
* Does a namespace have to be a valid identifier?

There are certainly questions I am missing, but I would like to focus on the "behavior" of imported namespaces independent of how/where they are imported. Questions about how imports are structured on the filesystem how those end up on the server or how they are downloaded are all out of scope for this issue.

**Comment by nathanielc** [comment]
With those questions up I'll put up my thoughts on some of them:

> Can assignment be made into an imported namespace?

This is essentially do we want to support monkey patching? I think not, I don't see much value in that. Allowing for this sort of thing encourages package/namespace level state to be exposed with the expectation that is can be modified by the user. I think that model in general is problematic and especially in a more functional language, where all state is typically enclosed in the function state.

> Do we want to support relative imports?

Again I do not think we want to support relative imports.  Python supports relative imports, but as a python dev I avoided them at all costs. They were confusing and tend to lead to patterns where users create toplevel packages that import lots of smaller packages to expose a "clean" package level API. I generally find that behavior in the python world to be quite frustrating, because there is so much indirection when looking for the implementation of some imported type that is takes significant effort to trace it out. For example see this popular SO question from a very confused user with Python relative imports. https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time 

In contrast Go's use of absolute paths make it much easier to track down the source. We want users reading Flux source, not tracing long import chains.

Flux code should be simple,there should not be a need to take a large API surface and reduce it down to some "clean" API surface to expose.

> Can I refer to imported namespaces of namespaces I import?

Here I also say no. I do not see any value in it and it starts to open up questions about maintaining all the imported namespaces recursively in they have their own state. In short it adds complexity and little value.

> Can you import all the identifiers from a namespace into the current namespace? What is the syntax for that? Python uses from foo import * Go uses import . "foo"

Personally I have never need to do this in Go. I find that using the package name to add clarity to the code being read. With wildcard imports you are always left guessing which package a given identifier came from. I prefer the clarity that Go provides. Again this goes back to making it easy for devs to follow imports back to source code.


> Can you rename the imported namespace? What is the syntax for that? Python's import foo as bar or Go's import bar "foo" something else?

I think this is a must, unless we do the C++ thing and allow namespaces to be specified in their hierarchy we will inevitably run into the case were you want to import to different namespaces, that have the same base name. As such you need a mechanism to rename them in the scope of the current script.

I don't care what the syntax is.

> Does a namespace have to be a valid identifier?

Yes, a package/namespace name is used solely for identifying it, so it should always be an identifier.


 In general I find Python's model to be overly complex (mixing of modules and packages, files and dirs) and I find that Go's is simple and straightforward to follow. And at this point in my career I have written much large Go projects than Python projects. I find that Go's simplicity scales well. So I expect it to scale well for Flux too. That is my general perspective, I am open to hear others as well.

**Comment by jsternberg** [comment]
I completely agree with everything @nathaniel said in his answers with the addition that we should have some way to specify that a function is private to the package so it can be used internally.

**Comment by jlapacik** [comment]
Ok so it sounds like everybody is in consensus on the following points:

> Can assignments be made into imported namespaces?

No

> Do we want to support relative imports?

No

> Can I refer to imported namespaces of namespaces I import?

No

> Can you import all the identifiers from a namespace into the current namespace?

No

> Can you rename the imported namespace?

Yes

> Does a namespace have to be a valid identifier?

Yes

A few unanswered questions:

* Does all Flux code need to be defined under a namespace? 
* Is there a special `main` package?
* Can namespaces modify options?

For the first question, I would say yes all Flux code needs to be defined under a namespace. I'm not sure how importing code not defined under a namespace would work.

For the second question, I would also say yes this is probably required. Otherwise executable code defined in any package would either always have to run no matter if that package was being executed (it seems like we wouldn't want this), or only the code in the executing package would be allowed to run (this seems better than the first option but it would probably be a better design to have executable code defined in a singular place).

And for the third question, because options modify the execution context of a query, it probably makes more sense to have a `main` package where the entry point of your program is defined, and then only allow options to be modified in this package. Without the `main` package, options could be modified in any package and I see this producing unexpected behavior of Flux scripts that import these packages.

**Comment by jsternberg** [comment]
A part of me thinks that we should allow an imported package to modify an option because the side effects might be useful (think `init()` in Go), but it may be something to disallow for now since it is something we can enable in the future if it is needed.

I would say yes for special main package and all flux code needs to be defined in a package. I would avoid using the word namespace because it implies something different when talking about languages. Modules or packages is usually used for code that is put into a namespace automatically.

**Comment by nathanielc** [comment]
@pauldix Do you have thoughts on the summary here https://github.com/influxdata/platform/issues/510#issuecomment-411553695 ?

Some of the "answers" go against some of your examples.

**Comment by jlapacik** [comment]
@nathanielc are you saying that any package should be able to define executing code? But that only the `main` package defines a program's entry point?

**Comment by nathanielc** [comment]
@jlapacik Yes, with a caveat about side effects. All statements in the imported package must be executed. Side effects are only captured if a side-effect function is called OR the statement is part of the main package. 

That behavior is basically what we already have. Meaning that if this code exists in a package `foo`:

```
package foo
bar = from(bucket:"foo") |> last()
```

No query is executed, because no side effect function was called. Whereas if that code where in the `main` package the query would be executed.

Then in the `main` package if this is done:

```
import "foo"

foo.bar
```

Now the query is executed because the side-effects are captured from expression statements in the `main` package.

But if the package `foo` were to use the `to` function which has a side effect then it would be executed as a side effect of importing.

```
package foo

from(bucket:"foo") |> to(bucket:"bar")
```

This would be a poor design of a package as just importing the package will copy the bucket `foo` into `bar`. The package developer should do this instead:

```
package foo
copy = () => from(bucket:"foo") |> to(bucket:"bar")
```

Then the `main` package that imports `foo` has to do `foo.copy()` in order for that query to execute.

In general we support explicit side-effects from all packages, and implicit side-effects from the `main` package. This enables useful behaviors. For example imagine a package named `telegraf`.

```
package telegraf

bucket = from(bucket:"telegraf")

cpu = bucket |> filter(fn:(r) => r._measurement == "cpu")
mem = bucket |> filter(fn:(r) => r._measurement == "mem")
```

Now in the `main` package a developer can do this:

```
import "telegraf"

telegraf.cpu |> range(start: -1m) // get last 1m of cpu data
telegraf.mem |> range(start: -1m) // get last 1m of mem data

telegraf.bucket |> filter(fn: (r) => r._measurement == "myplugin") |> range(start: -1m) // get last 1m of data from my custom plugin to telegraf.
```

The simple solution is to allow side-effects, but then expect users to write good packages that do not create side-effects unless it is the primary purpose of the package.

**Comment by jsternberg** [comment]
I don't think there's any controversy over explicit side effects. I might not understand options very well, so bear with me on this.

What you describe of using `to` or `yield` makes sense. Either one of those two is an explicit call and would be part of a function. Those get called explicitly from the main package and should have side effects because it is part of the call itself. We shouldn't disable `yield` just because it's not in a main package. But, I think the question is whether or not options should be capable of being _modified_ from a package. So imagine that I have the now option and I import a package. Should that package be able to redefine now? I'm not sure it should be able to. Once you add that kind of behavior, you also have to define the behavior of which order imports are loaded in. This is notable because C++ never defined how static declarations were initialized and every language that's come after it has made sure to define that because of how much trouble it got them in in C++.

I think we should avoid that entire fiasco. Explicit side effects from functions are fine, but we should avoid allowing one package to modify the options from another package through only an import. Packages will be able to define their own options.

It might be something that we may eventually find useful, but I think it's easier to play it safe and allow it once we get a feature request than to allow it before fully understanding what we're getting ourselves into.
