### ISSUE TITLE
query: internal API to identify affected buckets of a script

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#565]
As part of validating authorizations on tasks, we need to validate that the user has appropriate read and write permissions on affected buckets. While it's probably possible to iterate through a query spec and extract the arguments from the `from` or `to` functions, it would be better if there were a consistent API so that task code wouldn't have to hardcode a function list.

**Comment by nathanielc** [comment]
We need an interface for pass/fail of a query Spec given a set of authorizations. The list of buckets used will be the first thing to "authorize" for queries.

**Comment by wolffcm** [comment]
@mark-rushakoff I had some discussion with @nathanielc today about how authorization might best be handled in Flux.  Here's where we landed:
- `queryd` will perform per-bucket authorization checks internally, just before making storage requests.  All storage requests will need to pass an authorization check before they can proceed.  The goal here is for the mechanism to be simple and therefore difficult to subvert.
- A separate public API will be made available to tasks in order to pre-check authorization for a given query spec, similar to the one described above.  This will allow a task to fail early if the user doesn't have required authorizations.  

It turns out that it's difficult to ensure that a query spec reports the buckets it will read or write in a way that's reliably bulletproof, hence this two-pronged approach.  

Would handling authorization this way suit the needs of tasks?
