### ISSUE TITLE
Introduce single positional argument syntax?

### ISSUE THREAD

**Issue by pauldix** [influxdata/platform#702]
This is an idea I've been kicking around that I want to float. Frequently, it would be nice to be able to call functions that take one argument without having to pass in the name. There are two primary reasons to have named arguments only:

* Readable code - you know what the arguments are without having to look up function definitions
* Additive arguments don't break old code - if you add a new argument (with a default value) to a function, that won't be a breaking change. It makes improving functions over time more flexible.

Although I realized that we kind of have a single positional argument in functions already. That is the pipe-forwardable argument. Say we have this:

```
incr = (column="_value", <-tables) =>
    tables |> map(fn: (r) => r[[column]] = r[[column]] + 1)

// which can be called like
data |> incr()
// or like this
incr(tables:data)
```

When we pipe-forward the data into the function, it's not named, other than the variable name `data`.

The basic idea I have is that we could say that it's possible to have an argument passed into a function without a name, so long as it is the first thing passed **AND** the function has a pipe-forwardable argument. So you could call `incr(data)`.

Two disadvantages to this: more syntax for users to learn and you wouldn't be able to have a function be both pipe-forwardable AND have a positional argument. However, this might be useful for functions that sit around just to be called when their return values are passed as arguments to other functions.

Thoughts?

**Comment by docmerlin** [comment]
What would be the way forward to add optional args to such a function, without making a reading change?

**Comment by fntlnz** [comment]
I’m not sure if it’s just my brain but when I see a kind of pipe operator like `|>` or `|` I always expect for it to pass the result of the expression on the left as first parameter of the expression on the right if there’s only one parameter to pass.


Also I think that this kind of syntactic sugar encourages to create functions that are more single responsibility and thus very little and composable because in that way one can define a longer operation as multiple functions with one parameter resulting in a stream of operations instead of a monolithic one.

So I would say: implementing this has also the advantage of encouraging programming in a composable way instead of nesting operations in the same function and this seems a very key factor for this kind of language.

**Comment by pauldix** [comment]
@docmerlin you'd need to be able to mix the first non-named argument with named ones. So going back to my previous example, you could call `incr(data, columns: ["foo", "_value"])`

**Comment by aanthony1243** [comment]
the feature by itself bothers me less than the fact that adding it means there would be 3 ways to do the same thing.  to me this creates a learning challenge for new users, who will wonder which way is the "best" way, and why the other ways are there and when they should use them.

**Comment by pauldix** [comment]
@aanthony1243 yeah that was my concern too. My internal debate was if that complexity was worth having the ability to have succinct function/calls like `length(foo)` or whatever. Now I'm leaning towards no.

**Comment by nathanielc** [comment]
> When we pipe-forward the data into the function, it's not named, other than the variable name data.

This is wrong, and the example syntax is wrong as well which leads to the misunderstanding above.

The example should read like:

```
incr = (column="_value", tables=<-) =>
    tables |> map(fn: (r) => r[[column]] = r[[column]] + 1)

// which can be called like
data |> incr()
// or like this
incr(tables:data)
```

Now it is clear that `tables` is the name of the pipe forwarded argument. 

I say no to this change. So far we have embraced keyword arguments and I think we should continue to do so. If we have a single exception then we open the door to add more exceptions. 

So far we have used short keyword argument names for single argument functions so that it is clear and not in the way. For example all the type conversions take a single `v` for value argument. They read like this:

```
myInt = int(v: 42.5)
myFloat = float(v: 42)
```

Its consistent and not too verbose.

Also IDEs are doing are automatically adding the parameter names to call sites anyways for a few select cases. For example Goland adds the argument name to call sites that use literals as well as a few other places. See ![goland](https://cdn-images-1.medium.com/max/1600/1*XVKTvytRhK6W1H9wPzcggg.png) from the `Misc` section in this post https://medium.com/@andrey_cheptsov/golands-take-on-go-development-7d2611b14b99. 


Another place we will need to embrace keyword arguments is in function signatures.

Take this example from https://github.com/influxdata/platform/pull/86. It defines a predicate function as an argument so it can pass that predicate down to the filter function. 

```
tagValues = (db, key, predicate=(r) => true) =>
	from(db:db)
	  |> range(start:-24h)
	  |> filter(fn: predicate)
	  |> group(by:[key])
	  |> distinct(column:key)
	  |> group(by:["_stop","_start"])

```

The interesting bit here is that the argument name in the anonymous function is part of the function signature. So this is valid:

```
tagValues(db:"foo", key: "host", predicate: (r) => r._measurement == "cpu")
```

but this is not since the `r` parameter name cannot change

```
tagValues(db:"foo", key: "host", predicate: (x) => x._measurement == "cpu")
```

I think in practice it will be rare to want to use different argument names. The difference between Flux and other languages is that in Flux you have to use the same name, in other languages it is only a convention. 


So my round about point is that if we are going to embrace keyword arguments to the point that the argument name is apart of the function signature, then we should not add exceptions for smaller convenience syntax like single argument functions. Otherwise it become hard for the user to reason about when keyword argument concepts are followed and when they are not.

**Comment by pauldix** [comment]
@nathanielc hah, I'm thoroughly convinced that this is a horrible idea. Closing out :)
