### ISSUE TITLE
task: respect in-progress runs when claiming task in scheduler

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#710]
If the StoreTaskMeta.CurrentlyRunning slice has any entries, they should be respected when a task is claimed. This will enable recovery of in-progress runs after a restart.

**Comment by lyondhill** [comment]
I believe they are already 'respected' In that when the is picked up it picks up the task and does not attempt to run the tasks that are currently 'running'. I think the proper action here is to probably wipe the 'currently running' list when it is picked up by a new scheduler.

In the scenario that a task has concurrency set to 2 and is in progress on 1 run when the node crashes. The next time that task is picked up it will only be able to effectively run 1 concurrency because the node that should have removed the run from the list died before it could. 

The behavior should be that when a task is 'claimed' the "currently running" should be retried by the scheduler, then the normal operation of picking up work and scheduling new tasks.

@mark-rushakoff Is this what you were thinking?

**Comment by lyondhill** [comment]
I guess the other option is that we just wipe "currently running" on claim and just resume for the 'latest completed'.
