### ISSUE TITLE
Update buckets retention policies to use duration strings

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#796]

**Comment by desa** [comment]
Currently `Buckets`
https://github.com/influxdata/platform/blob/7bbd08798031ccf7f3795df8af53fd4f0f9a048a/bucket.go#L16-L24
Have a single `RetentionPeriod`. This should be modified so that buckets will have multiple retention periods as documented here
https://github.com/influxdata/platform/blob/f437888ee24e812fb8ddaa03468e7acd1103ef91/http/swagger.yml#L2216-L2263
