### ISSUE TITLE
Figure out what to do about the storage read path

### ISSUE THREAD

**Issue by e-dard** [influxdata/platform#899]
In the current storage engine prototype we had to pull a bunch of storage read code from OSS into platform. This now leaves us with  _three_ implementations of the read service. We need to unify the OSS and Platform implementations so that both Platform and OSS 1.7 can use them correctly.

Some issues to talk about:
- [x] storage writes as _f and _m, but it is supposed to be returned as _field and _measurement
- [x] it reads out of the same fixed measurement (clarity on `Read{Request,Source}` protobufs)

**Comment by stuartcarnie** [comment]
@e-dard some thoughts:

`_f` and `_m` is intended to be passed to `flux`, which will materialize the tags to `_field` and `_measurement` as late as possible. Nathaniel and I discussed this some time back and agreed the RPC interface doesn't need to transform them as flux is already doing that.

Most of the read service code should be shared between OSS and IDPE (cursors, aggregators, RPC writers, grouping, protobuf messages and service definition), with the exception of 

* series cursor, which has to deal with the different way series keys are written ( in IDPE and the optimization that `_f` is a real tag
* RPC interface to parse the different read source (org, bucket and partition) 
* Store, to handle how storage is partitioned totally differently

I would anticipate a few things with the move of key components of InfluxDB into platform

* we probably won't need the RPC interface in OSS, as nothing will use it and we have flux built-in
* similarly, as platform is expected to have a single binary, would we even need the RPC service there?
    * that would leave just the Store component to handle these requests
* anticipating that we'll be writing data the same as IDPE, we should be able to use share the Store, series cursor service in platform and IDPE?

**Comment by zeebo** [comment]
Summary of the current issue:

We want to use this function: 
https://github.com/influxdata/influxdb/blob/5bb62597c8dba125c6ab6e64172d0e10f9c71e3d/flux/control/controller.go#L17-L41

In order to use that, we need a `storage.Store`
https://github.com/influxdata/influxdb/blob/5bb62597c8dba125c6ab6e64172d0e10f9c71e3d/services/storage/store.go#L38-L42

But to implement that, we need to return `ResultSet` and `GroupResultSet`
https://github.com/influxdata/influxdb/blob/5bb62597c8dba125c6ab6e64172d0e10f9c71e3d/services/storage/store.go#L17-L36

But those refer to concrete `tsdb.Cursor` and `models.Tags`, and both of those packages have moved from influxdb into platform. It is not desirable to have platform import those packages from influx, so it becomes very difficult to implement.

Additionally, even if we could implement those interfaces, a ton of logic is captured in the `Read` and `GroupRead` implementations to create a `storage.Store` here.
https://github.com/influxdata/influxdb/blob/5bb62597c8dba125c6ab6e64172d0e10f9c71e3d/services/storage/store.go#L62-L68

But to use that functionality,
1. we need for it to exist somewhere that is not importing a lot of influxdb related packages if possible
2. a `*tsdb.Store`, which is no longer a concept we wish to support.

So, I'm not sure what the right refactoring is, but there's a lot of code bundled up with specific imports.

**Comment by zeebo** [comment]
It seems like `_m` and `_f` aren't late materialized, yet. But that will be an easy change. Otherwise, we're OK with how it is for now, and we'll pull in and refactor the other code so that it can be shared. Both of the above issues (`_m`/`_f` and appropriate measurement name) are both fixed.
