### ISSUE TITLE
Missing or broken link to SPEC.md

### ISSUE THREAD

**Issue by candlerb** [influxdata/platform#912]
At https://github.com/influxdata/platform/tree/master/query#flux---influx-data-language it says of flux:

> A complete specification can be found in [SPEC.md](https://github.com/influxdata/platform/blob/master/query/docs/SPEC.md).

but that link gives a 404.

**Comment by goller** [comment]
Hi @candlerb, thanks for writing in!

We've moved the flux language into its own repository here: https://github.com/influxdata/flux

We are building up flux in its own repository so that it can be more easily embedded in other projects.

I've updated the link and here is the PR : https://github.com/influxdata/platform/pull/913
